# permissions for end users to edit buckys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bucky-editor-role
rules:
- apiGroups:
  - buckycontroller.k8s.io
  resources:
  - buckys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - buckycontroller.k8s.io
  resources:
  - buckys/status
  verbs:
  - get
