# permissions for end users to view buckys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bucky-viewer-role
rules:
- apiGroups:
  - buckycontroller.k8s.io
  resources:
  - buckys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - buckycontroller.k8s.io
  resources:
  - buckys/status
  verbs:
  - get
